version: '3'
services:
  web:
    build: .
    image: django
    command: gunicorn faas.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env


