version: '3'
services:
  web:
    build: .
    image: django
    command: gunicorn faas.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
  db:
    image: postgres:14.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgres/data/
    expose:
      - 5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_HOST=${HOST}
  redis:
    image: redis:alpine
  celery:
      build: .
      command: celery -A faas worker -l info -E -B
      volumes:
        - .:/usr/src/app/
      depends_on:
        - redis
