version: '3'
services:
  web:
    build: .
    image: django
    command: gunicorn faas.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
  db:
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${SER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_HOST=${HOST}

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  celery:
      build: .
      restart: always
      command: celery -A faas worker --loglevel=INFO -E -B
      volumes:
        - .:/usr/src/app/
      depends_on:
        - redis
      links:
        - redis


